# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 02:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0009_auto_20171010_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='recommender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_membership_set', to='model.Idol'),
        ),
    ]
